# Generated by Django 4.2.15 on 2024-09-19 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrewApplicationDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="가입 메시지를 입력해주세요.", null=True
                    ),
                ),
                (
                    "is_pending",
                    models.BooleanField(
                        default=True, help_text="아직 수락/거절 되지 않았다면 True."
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=False, help_text="수락 여부를 입력해주세요."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, default=None, help_text="리뷰한 시간을 입력해주세요.", null=True
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="지원자를 입력해주세요.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        help_text="크루를 입력해주세요.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crews.crewdao",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["reviewed_by", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrewApplication",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("applications.crewapplicationdao",),
        ),
    ]
