# Generated by Django 4.2.13 on 2024-09-01 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrewActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(help_text='활동 이름을 입력해주세요. (예: "1회차")')),
                ("start_at", models.DateTimeField(help_text="활동 시작 일자를 입력해주세요.")),
                ("end_at", models.DateTimeField(help_text="활동 종료 일자를 입력해주세요.")),
            ],
            options={
                "ordering": ["start_at"],
                "get_latest_by": ["end_at"],
            },
        ),
        migrations.CreateModel(
            name="CrewActivityProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="문제 순서를 입력해주세요.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CrewActivitySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(help_text="유저의 코드를 입력해주세요.")),
                (
                    "language",
                    models.TextField(
                        choices=[
                            ("nodejs", "Node.js"),
                            ("kotlin", "Kotlin"),
                            ("swift", "Swift"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("python", "Python"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                            ("csharp", "C#"),
                            ("ruby", "Ruby"),
                            ("php", "PHP"),
                        ],
                        help_text="유저의 코드 언어를 입력해주세요.",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(help_text="유저의 코드가 정답인지 여부를 입력해주세요."),
                ),
                (
                    "is_help_needed",
                    models.BooleanField(
                        default=False, help_text="유저의 코드에 도움이 필요한지 여부를 입력해주세요."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="활동 문제를 입력해주세요.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activities.crewactivityproblem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
