# Generated by Django 4.2.13 on 2024-09-01 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0001_initial"),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewactivitysubmission",
            name="user",
            field=models.ForeignKey(
                help_text="유저를 입력해주세요.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crewactivityproblem",
            name="activity",
            field=models.ForeignKey(
                help_text="활동을 입력해주세요.",
                on_delete=django.db.models.deletion.CASCADE,
                to="activities.crewactivity",
            ),
        ),
        migrations.AddField(
            model_name="crewactivityproblem",
            name="crew",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crews.crew"
            ),
        ),
        migrations.AddField(
            model_name="crewactivityproblem",
            name="problem",
            field=models.ForeignKey(
                help_text="문제를 입력해주세요.",
                on_delete=django.db.models.deletion.PROTECT,
                to="problems.problem",
            ),
        ),
        migrations.AddField(
            model_name="crewactivity",
            name="crew",
            field=models.ForeignKey(
                help_text="크루를 입력해주세요.",
                on_delete=django.db.models.deletion.CASCADE,
                to="crews.crew",
            ),
        ),
        migrations.AddConstraint(
            model_name="crewactivityproblem",
            constraint=models.UniqueConstraint(
                fields=("activity", "order"), name="unique_order_per_activity_problem"
            ),
        ),
    ]
