# Generated by Django 4.2.13 on 2024-09-01 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="문제 이름을 입력해주세요.", max_length=100)),
                ("link", models.URLField(blank=True, help_text="문제 링크를 입력해주세요. (선택)")),
                ("description", models.TextField(help_text="문제 설명을 입력해주세요.")),
                (
                    "input_description",
                    models.TextField(blank=True, help_text="문제 입력 설명을 입력해주세요."),
                ),
                (
                    "output_description",
                    models.TextField(blank=True, help_text="문제 출력 설명을 입력해주세요."),
                ),
                (
                    "memory_limit",
                    models.FloatField(help_text="문제 메모리 제한을 입력해주세요. (MB 단위)"),
                ),
                (
                    "memory_limit_unit",
                    models.TextField(
                        choices=[("MB", "메가 바이트"), ("s", "초")], default="MB"
                    ),
                ),
                (
                    "time_limit",
                    models.FloatField(
                        default=1.0, help_text="문제 시간 제한을 입력해주세요. (초 단위)"
                    ),
                ),
                (
                    "time_limit_unit",
                    models.TextField(
                        choices=[("MB", "메가 바이트"), ("s", "초")], default="s"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="이 문제를 추가한 사용자를 입력해주세요.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
