# Generated by Django 4.2.13 on 2024-09-01 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crews", "0001_initial"),
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crewapplication",
            name="applicant",
            field=models.ForeignKey(
                help_text="지원자를 입력해주세요.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crewapplication",
            name="crew",
            field=models.ForeignKey(
                help_text="크루를 입력해주세요.",
                on_delete=django.db.models.deletion.CASCADE,
                to="crews.crew",
            ),
        ),
        migrations.AddField(
            model_name="crewapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applicants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="crewapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_pending", True)),
                fields=("crew", "applicant"),
                name="unique_pending_application",
            ),
        ),
    ]
