# Generated by Django 4.2.13 on 2024-09-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrewApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="가입 메시지를 입력해주세요.", null=True
                    ),
                ),
                (
                    "is_pending",
                    models.BooleanField(
                        default=True, help_text="아직 수락/거절 되지 않았다면 True."
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=False, help_text="수락 여부를 입력해주세요."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, default=None, help_text="리뷰한 시간을 입력해주세요.", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["reviewed_by", "created_at"],
            },
        ),
    ]
