# Generated by Django 4.2.13 on 2024-09-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analyses", "0001_initial"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemanalysis",
            name="problem",
            field=models.ForeignKey(
                help_text="문제를 입력해주세요.",
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.problem",
            ),
        ),
    ]
