# Generated by Django 4.2.15 on 2024-09-19 08:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(help_text="유저의 코드를 입력해주세요.")),
                (
                    "language",
                    models.TextField(
                        choices=[
                            ("nodejs", "Node.js"),
                            ("kotlin", "Kotlin"),
                            ("swift", "Swift"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("python", "Python"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                            ("csharp", "C#"),
                            ("ruby", "Ruby"),
                            ("php", "PHP"),
                        ],
                        help_text="유저의 코드 언어를 입력해주세요.",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(help_text="유저의 코드가 정답인지 여부를 입력해주세요."),
                ),
                (
                    "is_help_needed",
                    models.BooleanField(
                        default=False, help_text="유저의 코드에 도움이 필요한지 여부를 입력해주세요."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="활동 문제를 입력해주세요.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activities.crewactivityproblemdao",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="유저를 입력해주세요.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionCommentDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="댓글을 입력해주세요.", max_length=1000)),
                (
                    "line_number_start",
                    models.IntegerField(
                        help_text="댓글 시작 라인을 입력해주세요.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "line_number_end",
                    models.IntegerField(
                        help_text="댓글 종료 라인을 입력해주세요.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="유저를 입력해주세요.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="제출을 입력해주세요.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.submissiondao",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("submissions.submissiondao",),
        ),
        migrations.CreateModel(
            name="SubmissionComment",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("submissions.submissioncommentdao",),
        ),
    ]
