# Generated by Django 4.2.15 on 2024-09-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemAnalysisDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(0, "분석 중"), (1, "쉬움"), (2, "보통"), (3, "어려움")],
                        help_text="문제 난이도를 입력해주세요.",
                    ),
                ),
                (
                    "time_complexity",
                    models.CharField(
                        help_text=(
                            "문제 시간 복잡도를 입력해주세요. ",
                            "예) O(1), O(n), O(n^2), O(V \\log E) 등",
                        ),
                        max_length=100,
                    ),
                ),
                (
                    "hint",
                    models.JSONField(
                        default=list, help_text="문제 힌트를 입력해주세요. Step-by-step 으로 입력해주세요."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="문제를 입력해주세요.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problemdao",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Problem analyses",
                "ordering": ["-created_at"],
                "get_latest_by": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTagDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="알고리즘 태그 키를 입력해주세요. (최대 20자)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        help_text="알고리즘 태그 이름(국문)을 입력해주세요. (최대 50자)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="알고리즘 태그 이름(영문)을 입력해주세요. (최대 50자)",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTagRelationDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="analyses.problemtagdao",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to="analyses.problemtagdao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemAnalysisTagDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyses.problemanalysisdao",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="문제의 DSA 태그를 입력해주세요.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analyses.problemtagdao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemAnalysis",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("analyses.problemanalysisdao",),
        ),
        migrations.CreateModel(
            name="ProblemAnalysisTag",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("analyses.problemanalysistagdao",),
        ),
        migrations.CreateModel(
            name="ProblemTag",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("analyses.problemtagdao",),
        ),
        migrations.CreateModel(
            name="ProblemTagRelation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("analyses.problemtagrelationdao",),
        ),
    ]
