name: CI via SSH (Deploy)

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: CI via SSH (Deploy)
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: sudo /root/be-django/app/tools/update
