name: CD via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI via SSH (Deploy)
    runs-on: ubuntu-latest
    steps:
    - name: Apply update to actual server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: sudo /root/be-django/app/tools/update
